# Name			: Grace Brown
# Filename		: Makefile
# Date Created	: 9/8/2026
# Date Updated	: 9/8/2026

all:	Movie

Movie:	Driver.cpp
		g++ -W -o movie Driver.cpp Movie.cpp Showing.cpp Theater.cpp

run:	movie
		./movie

clean:	movie
		rm -f ./movie
