# Name			: Grace Brown
# Date Created	: April 16 2026
# Purpose		: Compilation instructions for Lab 10

all:	Furby

Furby:	Lab10.cpp 
		g++ -Wall -o furby Lab10.cpp

run:	furby
		./furby

clean:	furby
		rm -f furby