# 			Name: Grace Brown
# 	Date Created: 26 March 2026
#  Date Modified: 27 March 2026
# 	   File Name: makefile
#		 Purpose: Compiles lab 8

all:		Budget

Budget:		driver.cpp functions.cpp
			g++ -Wall -o budget driver.cpp functions.cpp

run:		Budget
			./budget	

clean:		Budget
			rm -f ./budget